### PR TITLE
Feature concert api

### PR DESCRIPTION
**Pull request by JDR8888**

### CODE REVIEW

**Comment by JDR8888** [comment]
after clicking rsolve conflicts button, for each file you can select "mark resolved" - html file I added an img placeholder element and linked jQuery

**Review by emmaparis — CHANGES_REQUESTED** [review]
Looks like there's a conflict w/ the main, can you pull the main and resolve the conflict?

**Comment by JDR8888** [comment]
Looks like conflicts should be resolved, can you pls review again and accept kthanks

**Review by emmaparis — APPROVED** [review]
Great job!

**Pull request merged**
